/**
 * プロジェクト規模を定義したEnum。
 *
 * @generated by enum/generate.ts from openapi.yaml x-enums
 * @source ProjectClass.java
 */
export const PROJECT_CLASS = {
  /**
   * SS。
   */
  "ss": "SS",
  /**
   * S。
   */
  "s": "S",
  /**
   * A。
   */
  "a": "A",
  /**
   * B。
   */
  "b": "B",
  /**
   * C。
   */
  "c": "C",
  /**
   * D。
   */
  "d": "D",
} as const;

/**
 * プロジェクト規模を定義したEnum のコード値型。
 */
export type ProjectClassValue = keyof typeof PROJECT_CLASS;
