/**
 * プロジェクトのソートキーを定義したEnum。
 *
 * @generated by enum/generate.ts from openapi.yaml x-enums
 * @source ProjectSortKey.java
 */
export const PROJECT_SORT_KEY = {
  /**
   * プロジェクトＩＤ。
   */
  "id": "プロジェクトＩＤ",
  /**
   * プロジェクト名。
   */
  "name": "プロジェクト名",
  /**
   * プロジェクト開始日。
   */
  "startDate": "プロジェクト開始日",
  /**
   * プロジェクト終了日。
   */
  "endDate": "プロジェクト終了日",
} as const;

