/**
 * プロジェクト種別を定義したEnum。
 *
 * @generated by enum/generate.ts from openapi.yaml x-enums
 * @source ProjectType.java
 */
export const PROJECT_TYPE = {
  /**
   * 新規開発PJ。
   */
  "development": "新規開発PJ",
  /**
   * 保守PJ。
   */
  "maintenance": "保守PJ",
} as const;

