/**
 * 並び順を定義したEnum。
 *
 * @generated by enum/generate.ts from openapi.yaml x-enums
 * @source SortOrder.java
 */
export const SORT_ORDER = {
  /**
   * 昇順。
   */
  "asc": "昇順",
  /**
   * 降順。
   */
  "desc": "降順",
} as const;

